build:
  unit_tests:
    image: jodersky/ci:0.1
    commands:
      - sbt +test

  publish:
    when:
      event: push
      success: true
    environment:
      GPG_SSB: "$$GPG_SSB"
      BINTRAY_KEY: "$$BINTRAY_KEY"
    commands:
      - .drone/authenv.sh
      - sbt +publishSigned
