pipeline:
  build:
    image: jodersky/ci
    commands:
      - sbt +test

  publish:
    image: jodersky/ci
    when:
      event: tag
      status: success
    environment:
      GPG_ID: 0xBEDDC1EFEE0D53FE6F853B0D71C38F1DB2C92742
      #GPG_KEY: "$$GPG_KEY"
      # Although the key is already encrypted in drone, giving it a password
      # makes it easier to handle outside of drone. E.g. gpg2 has issues
      # with password-less keys https://bugs.gnupg.org/gnupg/issue2070
      #GPG_PASSWORD: "$$GPG_PASSWORD"
      #SONATYPE_USERNAME: "$$SONATYPE_USERNAME"
      #SONATYPE_PASSWORD: "$$SONATYPE_PASSWORD"
    commands:
      - echo "$GPG_KEY" | base64 -w 0 -d | gpg --batch --import
      - sbt +publishSigned
      - echo "Done"
