build:
  unit_tests:
    image: jodersky/ci:0.2
    commands:
      - sbt +test

  publish:
    image: jodersky/ci:0.2
    when:
      event: push
      success: true
    environment:
      GPG_SSB_ENC: "$$GPG_SSB_ENC"
      BINTRAY_KEY: "$$BINTRAY_KEY"
    commands:
      - .drone/authenv.sh
      - sbt +publishSigned
